services: 
 fastapiservice: 
  build: 
   context: .
  container_name: fastapiservice
  volumes:
   -  .:/usr/src/app 
  ports:
   - "8000:8000" 
  depends_on:
   - mysqlservice 
  networks:
   - rede_interna 
  command: ["uvicorn","main:app","--reload"]

 mysqlservice:
  image: mysql:latest
  container_name: mysqlservice
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: "5912"
  ports:
   - "3306:3306"
   - "33060:33060"
  volumes:
   - mysql_data:/var/lib/mysql
   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  networks:
   - rede_interna

volumes:
 mysql_data:

networks:
  rede_interna:
    external: true

