services: 
 fastapiservice: 
  build: 
   context: .
  container_name: fastapiservice
  volumes:
   -  .:/usr/src/app 
  ports:
   - "8000:8000" 
  depends_on:
   - mysqlservice 
  networks:
   - rede_compartilhada_container 
  command: ["uvicorn","main:app","--reload"]

 mysqlservice:
  image: mysql:latest
  container_name: mysqlservice
  restart: no
  enviroment:
   MYSQL_ROOT_PASSWORD: "5912"
  ports:
   - "3306:3306"
   - "33060:33060"
  volumes:
   - mysql_data:/var/lib/mysql
   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  networks:
   - rede_compartilhada_container

volumes:
 mysql_data

networks:
 rede_compartilhada_container
 # driver: bridge
  external: true
   
